=== bulldize/CEJ_ABC/schemas/points.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "points",
  "type": "object",
  "required": ["case_id", "coord_type", "space", "points"],
  "properties": {
    "case_id": {"type": "string"},
    "coord_type": {"type": "string", "enum": ["voxel", "world"]},
    "space": {"type": "string", "enum": ["roi", "full"]},
    "points": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "array",
          "items": {"type": "number"},
          "minItems": 3,
          "maxItems": 3
        }
      }
    }
  }
}

=== bulldize/CEJ_ABC/migration_manifest_20260603_054411/paper_artifacts/source_paths/root/cej_runs/run_unsup_001/manual_case_dirs/ToothFairy3F_008/points.json
{"case_id": "ToothFairy3F_008", "coord_type": "voxel", "space": "full", "points": {"11": [[208.2785186767578, 23.6742000579834, 69.28601837158203], [233.5072479248047, 26.397607803344727, 65.54212188720703], [232.09393310546875, 27.38010025024414, 64.29415893554688], [208.03591918945312, 22.523418426513672, 68.45404815673828], [231.21278381347656, 30.08558464050293, 64.71014404296875], [229.83071899414062, 32.51318359375, 64.58309936523438], [216.06942749023438, 21.90283966064453, 54.696311950683594], [228.0975799560547, 35.499271392822266, 63.684303283691406], [217.53048706054688, 21.70473861694336, 54.696311950683594], [224.85806274414062, 38.92231369018555, 63.08510208129883], [218.37918090820312, 20.240276336669922, 54.99591064453125], [222.50503540039062, 40.13481521606445, 62.186302185058594], [219.2999725341797, 20.62271499633789, 54.99591064453125], [218.17428588867188, 40.22871398925781, 62.485904693603516], [220.5306396484375, 20.596033096313477, 55.295509338378906], [214.20529174804688, 37.57072830200195, 63.684303283691406], [221.33587646484375, 22.053482055664062, 54.696311950683594], [211.72726440429688, 35.34814453125, 64.58309936523438], [222.1741485595703, 22.21991729736328, 54.39670944213867], [209.9622039794922, 32.71139144897461, 64.88270568847656], [222.9964141845703, 22.630046844482422, 54.097110748291016], [209.0206756591797, 28.342580795288086, 67.27949523925781], [225.3339080810547, 23.291973114013672, 54.097110748291016], [207.620849609375, 24.360605239868164, 68.47789764404297], [233.05897521972656, 25.551376342773438, 65.18230438232422], [209.127197265625, 19.097881317138672, 61.29420471191406], [232.44854736328125, 23.441375732421875, 61.199371337890625], [231.2921142578125, 23.6245174407959, 57.78825759887695], [211.49147033691406, 20.503795623779297, 58.2504768371582], [229.17970275878906, 23.631250381469727, 57.12711715698242], [211.8318328857422, 19.509056091308594, 57.451080322265625]], "12": [[233.6431121826172, 33.422119140625, 69.85418701171875], [245.8983612060547, 41.203189849853516, 66.68599700927734], [234.8701629638672, 31.754322052001953, 69.49980163574219], [243.85215759277344, 42.557186126708984, 64.51929473876953], [234.8677520751953, 29.954795837402344, 70.35393524169922], [243.16265869140625, 43.42887878417969, 62.45574951171875], [235.9527587890625, 29.925418853759766, 68.89009094238281], [242.48204040527344, 44.08066177368164, 62.751487731933594], [237.23068237304688, 28.9616641998291, 62.62904357910156], [241.1153564453125, 45.613067626953125, 61.692447662353516], [238.7982940673828, 26.598590850830078, 62.69252014160156], [239.55902099609375, 46.5381965637207, 61.792030334472656], [235.72732543945312, 46.04975891113281, 62.83549499511719], [242.96365356445312, 28.091150283813477, 57.4213981628418], [244.7804412841797, 29.962112426757812, 56.75468444824219], [233.44151306152344, 45.25966262817383, 63.5721321105957], [246.42251586914062, 31.01688003540039, 58.18793487548828], [231.63917541503906, 44.28463363647461, 63.33326721191406], [248.03517150878906, 32.2750129699707, 59.63569641113281], [231.2652587890625, 42.11423873901367, 64.17447662353516], [250.03125, 33.81346893310547, 64.88656616210938], [231.55662536621094, 39.77885818481445, 65.22333526611328], [249.31271362304688, 36.181678771972656, 64.32801055908203], [232.39498901367188, 38.04722213745117, 65.34066009521484], [248.64712524414062, 38.293418884277344, 66.12854766845703], [232.43882751464844, 36.368408203125, 66.9019546508789], [248.1031036376953, 39.80940628051758, 67.18199920654297], [233.39080810546875, 35.310585021972656, 67.5260238647461], [249.75753784179688, 31.691152572631836, 61.8859977722168], [249.15643310546875, 32.466766357421875, 60.57114791870117], [238.62782287597656, 27.607603073120117, 60.630191802978516], [236.85635375976562, 28.575143814086914, 67.26094818115234]], "13": [[253.0061492919922, 42.759925842285156, 68.90660095214844], [263.983154296875, 56.19750213623047, 65.87264251708984], [254.62693786621094, 39.873291015625, 68.04103088378906], [261.9637756347656, 58.180870056152344, 65.21538543701172], [259.97918701171875, 59.43152618408203, 64.51423645019531], [256.8509826660156, 39.44313049316406, 64.57073974609375], [258.256103515625, 59.96757507324219, 64.60457611083984], [258.6866455078125, 37.655155181884766, 64.18389129638672], [255.91079711914062, 60.203861236572266, 63.01127624511719], [260.9342041015625, 39.062957763671875, 60.19367599487305], [252.39151000976562, 60.151771545410156, 62.92093276977539], [263.76300048828125, 40.60233688354492, 57.8741455078125], [264.9549560546875, 43.269866943359375, 55.89199447631836], [249.29185485839844, 59.16145324707031, 62.339080810546875], [246.3275604248047, 55.752281188964844, 65.82469940185547], [266.8396301269531, 45.86982345581055, 55.77159118652344], [246.4912872314453, 51.81018829345703, 68.74235534667969], [268.3785705566406, 48.156131744384766, 57.5368537902832], [247.68128967285156, 49.12415313720703, 66.85000610351562], [268.39739990234375, 50.461891174316406, 58.937103271484375], [249.91746520996094, 45.90660858154297, 68.05460357666016], [267.36749267578125, 53.578330993652344, 62.31748962402344], [251.36474609375, 44.56266784667969, 69.18939208984375], [266.1664733886719, 54.9528694152832, 63.91538619995117]], "14": [[266.50799560546875, 64.04026794433594, 65.59447479248047], [271.05438232421875, 77.0059585571289, 64.18193054199219], [268.07696533203125, 78.19424438476562, 63.14057540893555], [269.2214660644531, 61.65867233276367, 67.54529571533203], [270.61212158203125, 60.63726806640625, 67.44896697998047], [266.856689453125, 78.68953704833984, 64.40653991699219], [264.1481018066406, 79.29092407226562, 64.27903747558594], [273.6920471191406, 59.689640045166016, 67.06660461425781], [277.33746337890625, 59.9472541809082, 65.05270385742188], [261.33087158203125, 78.59410095214844, 64.08272552490234], [280.05938720703125, 61.881160736083984, 64.84161376953125], [258.3653259277344, 77.49063873291016, 63.86410140991211], [254.18228149414062, 74.67227172851562, 66.23053741455078], [282.2728271484375, 65.93743133544922, 63.80553436279297], [254.1781768798828, 69.5993423461914, 66.89311218261719], [280.7422790527344, 70.44487762451172, 64.10301971435547], [258.0189208984375, 65.98347473144531, 67.30078887939453], [278.2287902832031, 73.58609771728516, 65.79743957519531], [261.2165222167969, 64.93974304199219, 68.1148681640625], [276.80035400390625, 75.3416976928711, 66.6644515991211], [273.545166015625, 75.83811950683594, 65.34101867675781], [263.83026123046875, 64.13914489746094, 67.99333190917969], [272.2350158691406, 76.4352798461914, 65.89778900146484], [265.5801696777344, 64.44133758544922, 66.51959228515625]], "15": [[261.53009033203125, 97.30924224853516, 66.8397216796875], [288.1683654785156, 87.53801727294922, 65.31117248535156], [263.05023193359375, 93.91902160644531, 65.7283706665039], [289.735595703125, 90.40928649902344, 64.25970458984375], [264.9106140136719, 90.31792449951172, 67.52515411376953], [266.3786315917969, 89.27194213867188, 68.01181030273438], [286.5332336425781, 95.67631530761719, 68.16175842285156], [267.4841613769531, 87.9278793334961, 67.97357940673828], [284.5523986816406, 97.16511535644531, 66.21395874023438], [282.34088134765625, 98.18413543701172, 66.96356201171875], [269.6811218261719, 87.28829193115234, 67.66612243652344], [271.6897888183594, 85.82888793945312, 68.56219482421875], [280.1820373535156, 100.21459197998047, 68.4079360961914], [273.2406005859375, 85.39505767822266, 67.86082458496094], [277.8134460449219, 99.98746490478516, 66.99968719482422], [274.8196105957031, 85.04825592041016, 68.41626739501953], [276.2144470214844, 102.36041259765625, 68.04113006591797], [275.8993835449219, 84.6962890625, 67.31250762939453], [274.61083984375, 102.25525665283203, 66.62252044677734], [272.35003662109375, 102.95903778076172, 66.11750793457031], [277.66058349609375, 83.90606689453125, 67.8287353515625], [270.3664855957031, 102.99234008789062, 64.9343032836914], [279.1111755371094, 84.02794647216797, 67.36763000488281], [266.79351806640625, 103.16204071044922, 65.91141510009766], [282.0958251953125, 83.58960723876953, 65.34886932373047], [264.00970458984375, 101.34732055664062, 65.27347564697266], [285.5748291015625, 84.01626586914062, 66.29084014892578], [262.057861328125, 98.19351959228516, 64.7348861694336], [286.82220458984375, 87.27620697021484, 63.09907150268555], [290.1004943847656, 93.01705932617188, 65.76167297363281], [283.70684814453125, 84.50068664550781, 65.47273254394531]], "16": [[266.57025146484375, 128.85789489746094, 68.9236831665039], [295.944580078125, 116.46870422363281, 60.08663558959961], [263.56005859375, 125.39154052734375, 69.1102294921875], [297.40008544921875, 120.15577697753906, 61.63808822631836], [262.71173095703125, 122.23866271972656, 67.57217407226562], [297.0804748535156, 123.09703826904297, 62.1011848449707], [263.29351806640625, 119.19474029541016, 67.3736343383789], [295.6717834472656, 125.64190673828125, 60.91779708862305], [264.77752685546875, 116.81082153320312, 66.9031982421875], [294.863037109375, 127.68295288085938, 61.89655685424805], [268.2337951660156, 115.19615173339844, 66.67880249023438], [292.5990295410156, 129.353271484375, 62.63178253173828], [270.1615905761719, 113.36653137207031, 68.16809844970703], [291.11285400390625, 131.0292510986328, 62.77992248535156], [272.6687316894531, 112.02693939208984, 68.00243377685547], [288.4200439453125, 131.7892608642578, 62.090362548828125], [274.89129638671875, 110.83119201660156, 68.68972778320312], [286.27154541015625, 132.23928833007812, 62.46956253051758], [277.0411682128906, 109.89675903320312, 68.28811645507812], [284.5142822265625, 133.02130126953125, 62.295265197753906], [281.854248046875, 134.6621856689453, 62.4697151184082], [280.3554382324219, 108.11459350585938, 68.36125183105469], [283.2047424316406, 107.71812438964844, 67.14083862304688], [279.5362548828125, 134.80152893066406, 63.65
